language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.7
          packages:
            - cmake
            - cmake-data
            - clang-3.7
      env: COMPILER=clang++-3.7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - cmake-data
            - clang-3.6
      env: COMPILER=clang++-3.6

install:
    - if [ "$COMPILER" = "clang++-3.7" ]; then export CXX="clang++-3.7" CC="clang-3.7" SCAN="scan-build-3.7"; fi
    - if [ "$COMPILER" = "clang++-3.6" ]; then export CXX="clang++-3.6" CC="clang-3.6" SCAN="scan-build-3.6"; fi
  # Get boost
    - wget https://github.com/Viq111/travis-container-packets/releases/download/boost-1.57.0/boost.tar.bz2
    - tar -xjf boost.tar.bz2
    - rm boost.tar.bz2
    - export BOOST_ROOT=$(pwd)/boost
    
before_script:
    - mkdir build
    - cd build
    - $SCAN --use-cc=$CC --use-c++=$CXX cmake -DTESTS=ON -DCMAKE_CXX_FLAGS="-lrt -pthread" ..

script:
    - make && make test && $SCAN make

