language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - boost-latest
          packages:
            - cmake
            - cmake-data
            - libboost1.55-all-dev
            - g++-5
      env: CXX=g++-5 CC=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - boost-latest
            - llvm-toolchain-precise-3.7
          packages:
            - cmake
            - cmake-data
            - libboost1.55-all-dev
            - clang-3.7
      env: CXX=clang++-3.7 CC-3.7


before_script:
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build
    - cd build
    - cmake -DTESTS=ON -Dstdlib=libstdc++ ..

script: make && make test

