language: cpp

compiler:
  - gcc
  - clang

addons:
apt:
  sources:
    - george-edison55-precise-backports # cmake 3.2.3
  packages:
    - cmake

before_script:
    - mkdir build
    - cd build
    - cmake -DTESTS=ON ..

script: make

