language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data

install:
  - export LLVM_VERSION=3.7.0
  - export LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
  - export CXX=$HOME/clang-$LLVM_VERSION/bin/clang++
  - export LD_LIBRARY_PATH=$HOME/clang-$LLVM_VERSION/lib:$LD_LIBRARY_PATH
  - export PATH=$HOME/clang-$LLVM_VERSION/bin/:$PATH
  - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
  - mkdir $HOME/clang-$LLVM_VERSION
  - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang-$LLVM_VERSION --strip-components 1

  # Get boost
  - wget https://github.com/Viq111/travis-container-packets/releases/download/boost-1.57.0/boost.tar.bz2
  - tar -xjf boost.tar.bz2
  - rm boost.tar.bz2
  - export BOOST_ROOT=$(pwd)/boost
    
before_script:
  - mkdir build
  - cd build
  - cmake -DTESTS=ON -DCMAKE_CXX_FLAGS="-lrt -pthread -I $HOME/clang-$LLVM_VERSION/include/c++/v1 " ..

script:
  - make && make test

