language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.7
          packages:
            - cmake
            - cmake-data
            - clang-3.7
      env: COMPILER=clang++-3.7 CLANG=1

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    - PROJECT_DIR=`pwd`
    - BOOST=$HOME/boost
    - git clone -b boost-1.58.0 https://github.com/boostorg/boost.git $BOOST
    - cd $BOOST
    - git submodule update --init --merge
    - ./bootstrap.sh
    - ./b2 -with-atomic -with-container -with-filesystem -with-locale -with-system -with-thread stage
    
before_script:
    - cd $PROJECT_DIR
    - mkdir build
    - cd build
    - cmake -DTESTS=ON -DBOOST_ROOT=$BOOST -DBOOST_LIBRARYDIR=$BOOST/stage/lib ..

script: make && make test

