language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - libboost-dev
            - libboost-thread-dev
            - libboost-system-dev
            - libboost-filesystem-dev
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
            - libboost-dev
            - libboost-thread-dev
            - libboost-system-dev
            - libboost-filesystem-dev
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - cmake-data
            - libboost-dev
            - libboost-thread-dev
            - libboost-system-dev
            - libboost-filesystem-dev
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
            - llvm-toolchain-precise-3.7
          packages:
            - cmake
            - cmake-data
            - libboost-dev
            - libboost-thread-dev
            - libboost-system-dev
            - libboost-filesystem-dev
            - clang-3.7
      env: COMPILER=clang++-3.7

before_script:
    - mkdir build
    - cd build
    - cmake -DTESTS=ON ..

script: make && make test

