language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - cmake
            - cmake-data
      env: COMPILER=clang++-3.7

install:
    - export CXX="clang++-3.7" CC="clang-3.7"
    - wget http://llvm.org/releases/3.7.0/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $HOME/clang+llvm.tar.xz
    - mkdir $HOME/clang+llvm
    - tar xf $HOME/clang+llvm.tar.xz -C $HOME/clang+llvm --strip-components 1
    - export PATH=$HOME/clang+llvm/bin:$PATH
    
  # Get boost
    - wget https://github.com/Viq111/travis-container-packets/releases/download/boost-1.57.0/boost.tar.bz2
    - tar -xjf boost.tar.bz2
    - rm boost.tar.bz2
    - export BOOST_ROOT=$(pwd)/boost


    
before_script:
    - mkdir build
    - cd build
    - cmake -DTESTS=ON -DCMAKE_CXX_FLAGS="-lrt -pthread" ..

script:
    - make && make test

